function com_thomas_winecellar_widgetset_VinecellarWidgetset(){var O='bootstrap',P='begin',Q='gwt.codesvr.com.thomas.winecellar.widgetset.VinecellarWidgetset=',R='gwt.codesvr=',S='com.thomas.winecellar.widgetset.VinecellarWidgetset',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='com_thomas_winecellar_widgetset_VinecellarWidgetset',ob='Failed to load ',pb='head',qb='meta',rb='name',sb='com.thomas.winecellar.widgetset.VinecellarWidgetset::',tb='::',ub='gwt:property',vb='content',wb='=',xb='gwt:onPropertyErrorFn',yb='Bad handler "',zb='" for "gwt:onPropertyErrorFn"',Ab='gwt:onLoadErrorFn',Bb='" for "gwt:onLoadErrorFn"',Cb='#',Db='?',Eb='/',Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='com.thomas.winecellar.widgetset.VinecellarWidgetset.nocache.js',Jb='base',Kb='//',Lb='modernie',Mb='MSIE',Nb='Trident',Ob='yes',Pb='none',Qb='user.agent',Rb='webkit',Sb='trident',Tb='safari',Ub='msie',Vb=10,Wb=11,Xb='ie10',Yb=9,Zb='ie9',$b=8,_b='ie8',ac='gecko',bc='gecko1_8',cc=2,dc=3,ec=4,fc='webkitvariant',gc='std',hc='android2',ic='ios7hswa',jc='ios7safari',kc='selectingPermutation',lc='com.thomas.winecellar.widgetset.VinecellarWidgetset.devmode.js',mc='4C0A4FC2024C1E7C8F4805FADA41F06D',nc=':1',oc=':10',pc=':11',qc=':12',rc=':13',sc=':14',tc=':15',uc=':2',vc=':3',wc=':4',xc=':5',yc=':6',zc=':7',Ac=':8',Bc=':9',Cc=':',Dc='.cache.js',Ec='loadExternalRefs',Fc='end',Gc='http:',Hc='file:',Ic='_gwt_dummy_',Jc='__gwtDevModeHook:com.thomas.winecellar.widgetset.VinecellarWidgetset',Kc='Ignoring non-whitelisted Dev Mode URL: ',Lc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_thomas_winecellar_widgetset_VinecellarWidgetset.__sendStats=r;com_thomas_winecellar_widgetset_VinecellarWidgetset.__moduleName=S;com_thomas_winecellar_widgetset_VinecellarWidgetset.__errFn=null;com_thomas_winecellar_widgetset_VinecellarWidgetset.__moduleBase=U;com_thomas_winecellar_widgetset_VinecellarWidgetset.__softPermutationId=V;com_thomas_winecellar_widgetset_VinecellarWidgetset.__computePropValue=null;com_thomas_winecellar_widgetset_VinecellarWidgetset.__getPropMap=null;com_thomas_winecellar_widgetset_VinecellarWidgetset.__installRunAsyncCode=function(){};com_thomas_winecellar_widgetset_VinecellarWidgetset.__gwtStartLoadingFragment=function(){return null};com_thomas_winecellar_widgetset_VinecellarWidgetset.__gwt_isKnownPropertyValue=function(){return false};com_thomas_winecellar_widgetset_VinecellarWidgetset.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};com_thomas_winecellar_widgetset_VinecellarWidgetset.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[com_thomas_winecellar_widgetset_VinecellarWidgetset.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_thomas_winecellar_widgetset_VinecellarWidgetset.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(com_thomas_winecellar_widgetset_VinecellarWidgetset.__errFn){n.onerror=function(){com_thomas_winecellar_widgetset_VinecellarWidgetset.__errFn(nb,new Error(ob+code))}}p.getElementsByTagName(pb)[V].appendChild(n)}
com_thomas_winecellar_widgetset_VinecellarWidgetset.__startLoadingFragment=function(a){return D(a)};com_thomas_winecellar_widgetset_VinecellarWidgetset.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(qb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,bb);if(j.indexOf(tb)>=V){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;com_thomas_winecellar_widgetset_VinecellarWidgetset.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Jb);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_thomas_winecellar_widgetset_VinecellarWidgetset.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Lb]=function(){{var a=o.navigator.userAgent;if(a.indexOf(Mb)==-1&&a.indexOf(Nb)!=-1){return Ob}return Pb}};i[Lb]={none:V,yes:W};j[Qb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Rb)!=-1&&a.indexOf(Sb)==-1}())return Tb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Vb&&b<Wb)}())return Xb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Yb&&b<Wb)}())return Zb;if(function(){return a.indexOf(Ub)!=-1&&(b>=$b&&b<Wb)}())return _b;if(function(){return a.indexOf(ac)!=-1||b>=Wb}())return bc;return bb};i[Qb]={gecko1_8:V,ie10:W,ie8:cc,ie9:dc,safari:ec};j[fc]=function(){{var a=window.navigator.userAgent;if(/Trident/.test(a))return gc;if(/android 2\./i.test(a))return hc;if(/iP.+OS 7_0(?!.+Safari)/.test(a))return ic;if(/iP.+OS 7_.+Safari/.test(a))return jc;return gc}};i[fc]={android2:V,ios7hswa:W,ios7safari:cc,std:dc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};com_thomas_winecellar_widgetset_VinecellarWidgetset.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};com_thomas_winecellar_widgetset_VinecellarWidgetset.__computePropValue=k;o.__gwt_activeModules[S].bindings=com_thomas_winecellar_widgetset_VinecellarWidgetset.__getPropMap;r(O,kc);if(q()){return D(lc)}var l;try{h([Pb,bc,hc],mc);h([Ob,bc,hc],mc+nc);h([Pb,Xb,jc],mc+oc);h([Pb,Xb,gc],mc+pc);h([Pb,Tb,hc],mc+qc);h([Pb,Tb,ic],mc+rc);h([Pb,Tb,jc],mc+sc);h([Pb,Tb,gc],mc+tc);h([Pb,bc,ic],mc+uc);h([Ob,bc,ic],mc+vc);h([Pb,bc,jc],mc+wc);h([Ob,bc,jc],mc+xc);h([Pb,bc,gc],mc+yc);h([Ob,bc,gc],mc+zc);h([Pb,Xb,hc],mc+Ac);h([Pb,Xb,ic],mc+Bc);l=f[k(Lb)][k(Qb)][k(fc)];var m=l.indexOf(Cc);if(m!=-1){g=parseInt(l.substring(m+W),Vb);l=l.substring(V,m)}}catch(a){}com_thomas_winecellar_widgetset_VinecellarWidgetset.__softPermutationId=g;return D(l+Dc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Ec,P);r(Ec,Fc)}
B();com_thomas_winecellar_widgetset_VinecellarWidgetset.__moduleBase=C();t[S].moduleBase=com_thomas_winecellar_widgetset_VinecellarWidgetset.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Gc||o.location.protocol==Hc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Ic;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Jc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Kc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Lc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(pb)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Fc);A(H);return true}
com_thomas_winecellar_widgetset_VinecellarWidgetset.succeeded=com_thomas_winecellar_widgetset_VinecellarWidgetset();